### ISSUE TITLE
USB-C video

### ISSUE THREAD

**Issue by maartenweyns** [Feliks151450/Hackintosh-for-HP-zbook-studio-Z5#1]
Hi! I have the same laptop as you. Have you gotten USB-C video out to work? I have been struggling for so long with this.

**Comment by Feliks151450** [comment]
Hello, I failed to make the USB-C video out work. Maybe it is also wired to NIVIDIA graphic card or it need to make the thunderbolt mode work first. I will modified my decription about it.
